spring:
  application:
    name: product-service
  datasource:
#    url: jdbc:postgresql://localhost:5433/product
#    url: jdbc:postgresql://ep-shiny-dew-amtwkw3i-pooler.c-5.us-east-1.aws.neon.tech/product?sslmode=require&channel_binding=require
    url: jdbc:mysql://localhost:3306/productservice
#    username: neondb_owner
#    password: npg_ZUj2R9NiDwSh
    username: root
    password: Nanikera1234
  jpa:
#    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

